# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "0.0.0.0" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "Caitlin Smallcomb: Web Developer"
  avatar:
  gravatar: # Email MD5 hash
  description: "Portfolio for web developer Caitlin Smallcomb." # used by search engines

  # Header and footer text
  header_text: >
     Caitlin Smallcomb
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: csmallcomb@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: http://github.com/csmallcomb
  google_plus:
  instagram:
  linkedin:  http://www.linkedin.com/in/csmallcomb/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-106135625-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
